version: "3"
services:
  survival:
    build:
      context: .
    container_name: survival
    restart: unless-stopped
    volumes:
      - ./server:/server
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
